"""
Generate gaze heatmaps.

Input
-----
CSV generated by 03_assign_aois.py

Output
------
PNG heatmap overlaid on the stimulus image.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import cv2
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy.ndimage import gaussian_filter

from configs.paths import (
    ANALYSIS_EYE_TRACKING_DIR,
)

# ==========================================================
# Paths
# ==========================================================

OUTPUT_DIR = (
    ANALYSIS_EYE_TRACKING_DIR /
    "heatmaps"
)

IMAGE_FILES = {

    "new":
        Path(
            "experimento/cookie_nueva_original.png"
        ),

    "original":
        Path(
            "experimento/cookie_vieja_original.png"
        ),

}

# ==========================================================
# Helpers
# ==========================================================

def load_image(image_name):

    img = cv2.imread(
        str(
            IMAGE_FILES[image_name]
        )
    )

    if img is None:

        raise FileNotFoundError(
            IMAGE_FILES[image_name]
        )

    img = cv2.cvtColor(
        img,
        cv2.COLOR_BGR2RGB,
    )

    return img

def create_heatmap(
    xs,
    ys,
    width,
    height,
    bins=200,
    sigma=12,
):
    """
    Create a gaze heatmap using a 2D histogram followed by Gaussian blur.
    """

    # --------------------------------------------------
    # Keep only samples inside the image
    # --------------------------------------------------

    mask = (
        (xs >= 0)
        & (xs < width)
        & (ys >= 0)
        & (ys < height)
    )

    xs = xs[mask]
    ys = ys[mask]

    if len(xs) == 0:
        return np.zeros((height, width), dtype=np.float32)

    # --------------------------------------------------
    # Build 2D histogram
    # --------------------------------------------------

    heatmap, _, _ = np.histogram2d(
        ys,
        xs,
        bins=[bins, bins],
        range=[
            [0, height],
            [0, width],
        ],
    )

    # --------------------------------------------------
    # Resize to image size
    # --------------------------------------------------

    heatmap = cv2.resize(
        heatmap.astype(np.float32),
        (width, height),
        interpolation=cv2.INTER_CUBIC,
    )

    # --------------------------------------------------
    # Smooth
    # --------------------------------------------------

    heatmap = gaussian_filter(
        heatmap,
        sigma=sigma,
    )

    # --------------------------------------------------
    # Normalize
    # --------------------------------------------------

    if heatmap.max() > 0:
        heatmap /= heatmap.max()

    return heatmap

def plot_heatmap(
    df: pd.DataFrame,
    output_file: Path,
    title: str | None = None,
    only_aoi: bool = False,
):
    """
    Generate and save a gaze heatmap from a dataframe.

    Parameters
    ----------
    df : pd.DataFrame
        Eye-tracking dataframe.
    output_file : Path
        Output PNG path.
    title : str, optional
        Figure title.
    only_aoi : bool
        If True, only use samples inside AOIs.
    """

    if only_aoi:

        df = df[df["aoi"].notna()]

        if df.empty:

            print("No AOI samples.")

            return

    image_name = df["image"].iloc[0]

    image = load_image(image_name)

    h, w = image.shape[:2]

    xs = (
        df["x_analysis"] * w
    ).to_numpy()

    ys = (
        df["y_analysis"] * h
    ).to_numpy()

    heatmap = create_heatmap(
        xs,
        ys,
        w,
        h,
    )

    heatmap[heatmap < 0.05] = np.nan

    fig, ax = plt.subplots(
        figsize=(10, 8)
    )

    ax.imshow(image)

    ax.imshow(
        heatmap,
        cmap="inferno",
        alpha=0.70,
        extent=[0, w, h, 0],
        interpolation="bilinear",
    )

    ax.set_xlim(0, w)
    ax.set_ylim(h, 0)

    ax.axis("off")

    if title is not None:

        ax.set_title(
            title,
            fontsize=14,
        )

    output_file.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    plt.savefig(
        output_file,
        dpi=300,
        bbox_inches="tight",
    )

    plt.close()

    print(f"Saved: {output_file}")
    
# ==========================================================
# Visualization
# ==========================================================

def visualize(
    csv_file: Path,
    only_aoi: bool = False,
):

    df = pd.read_csv(csv_file)

    output_file = (
        OUTPUT_DIR /
        f"{csv_file.stem}_heatmap.png"
    )

    plot_heatmap(
        df=df,
        output_file=output_file,
        title=csv_file.stem,
        only_aoi=only_aoi,
    )

    # ==========================================================
# Main
# ==========================================================

def main():

    parser = argparse.ArgumentParser(

        description="Generate gaze heatmap."

    )

    parser.add_argument(

        "csv",

        type=Path,

        help="CSV generated by 03_assign_aois.py",

    )

    parser.add_argument(
    "--only-aoi",
    action="store_true",
    help="Generate heatmap using only samples inside AOIs.",
)

    args = parser.parse_args()

    if not args.csv.exists():

        raise FileNotFoundError(

            args.csv

        )

    visualize(

        args.csv,
        only_aoi=args.only_aoi,


    )

    print()

    print("=" * 60)

    print("HEATMAP COMPLETE")

    print("=" * 60)

    print()

    print("Saved to:")

    print(OUTPUT_DIR)

    print()


if __name__ == "__main__":

    main()