cache: true

base_path: null # set from environment variable

features: 
  - text:
    - name: 'language'
      language: 'es'
      feature_set: ['coherence', 'fluence', 'lexical', 'speechgraph', 'syntax', 'utils']

splitter:
  name: 'basicsampling' # 'upsampling'
  repetitions: 500

classifier:
  pca: True